CREATE TABLE IF NOT EXISTS admin_users (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(64) NOT NULL UNIQUE,
  email VARCHAR(128) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS customer_users (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(128) NOT NULL,
  email VARCHAR(128) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS customer_api_keys (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  merchant_name VARCHAR(128) NOT NULL,
  api_key VARCHAR(128) NOT NULL,
  active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_api_key (api_key),
  UNIQUE KEY uniq_merchant_name (merchant_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS orders (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  merchant_name VARCHAR(128) NOT NULL,
  transaction_network ENUM('TRON', 'BSC', 'Ethereum') NOT NULL,
  transaction_asset ENUM('USDT', 'USDC') NOT NULL,
  txid VARCHAR(128) NOT NULL,
  amount DECIMAL(18, 8) NULL,
  email VARCHAR(128) NOT NULL,
  beneficiary_name VARCHAR(128) NOT NULL,
  bank_country ENUM('Canada', 'United States') NOT NULL,
  bank_name VARCHAR(128) NOT NULL,
  iban VARCHAR(64) NOT NULL,
  swift VARCHAR(64) NOT NULL,
  reference_note TEXT NULL,
  status ENUM('Paid', 'Processing', 'Summitted', 'Failed', 'Funds Received') NOT NULL DEFAULT 'Processing',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
